//  storeSportsPie
export const CHANGE_CALORIE_NOW = 'CHANGE_CALORIE_NOW'
export const CHANGE_CALORIE_TARGET = 'CHANGE_CALORIE_TARGET'

//  storeSportsDetail
export const CHANGE_DETAIL_CALORIE_TIME = 'CHANGE_DETAIL_CALORIE_TIME'

// storeCalenderSportsSteps
export const CHANGE_CALENDER_STEPS = 'CHANGE_CALENDER_STEPS'
